workflows:
  expo_release_android:
    name: Expo Android Release
    working_directory: .
    environment:
      vars:
        EXPO_CLI_VERSION: 7
      node: 20.11.0
     
    cache:      
      cache_paths:
        - ~/.yarn
    scripts:
      - npm ci
      - npx expo prebuild --platform android || true
      - npx expo build:android --type app-bundle --no-publish --non-interactive
    artifacts:
      - build/**/*.aab
