workflows:
  expo_release_android:
    name: Expo Android Release
    working_directory: .
    environment:
      vars:
        EXPO_CLI_VERSION: 7
      node: 20.11.0
      # yarn_cache: true  ❌ احذف هذا السطر
    cache:        # ✅ بديل اختياري
      cache_paths:
        - ~/.yarn
    scripts:
      - npm install
      # EAS CLI not needed for local Gradle build
      - npx expo prebuild --platform android --no-install
      - cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
