version: 2.1
jobs:
  build:
    machine:
      image: cimg/android:2025.04.1
    steps:
      - checkout
      - run:
          name: Build Android App
          command: ./gradlew assembleDebug
workflows:
  version: 2
  build:
    jobs:
      - build