version: 2.1
jobs:
  build-android:
    docker:
      - image: circleci/android:api-34
    steps:
      - checkout
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
workflows:
  version: 2
  android-build:
    jobs:
      - build-android